// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlockCtaDocumentDataSlicesSlice = never;

/**
 * Content for Bloc CallTo Action documents
 */
interface BlockCtaDocumentData {
  /**
   * Titre field in *Bloc CallTo Action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: block_cta.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sous-titre field in *Bloc CallTo Action*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_cta.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Image field in *Bloc CallTo Action*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_cta.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Résumé field in *Bloc CallTo Action*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_cta.resume
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  resume: prismic.RichTextField;

  /**
   * Contenu field in *Bloc CallTo Action*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_cta.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Masquer bouton de lien field in *Bloc CallTo Action*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: block_cta.display_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_button_link: prismic.BooleanField;

  /**
   * Lien field in *Bloc CallTo Action*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Lien
   * - **API ID Path**: block_cta.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Slice Zone field in *Bloc CallTo Action*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: block_cta.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlockCtaDocumentDataSlicesSlice>;
}

/**
 * Bloc CallTo Action document from Prismic
 *
 * - **API ID**: `block_cta`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlockCtaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlockCtaDocumentData>,
    "block_cta",
    Lang
  >;

type BlockHeroDocumentDataSlicesSlice = never;

/**
 * Content for Bloc de présentation documents
 */
interface BlockHeroDocumentData {
  /**
   * Titre field in *Bloc de présentation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_hero.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sous-titre field in *Bloc de présentation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_hero.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Image field in *Bloc de présentation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_hero.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Bloc de présentation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: block_hero.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlockHeroDocumentDataSlicesSlice>;
}

/**
 * Bloc de présentation document from Prismic
 *
 * - **API ID**: `block_hero`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlockHeroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlockHeroDocumentData>,
    "block_hero",
    Lang
  >;

type BlockTestimonialDocumentDataSlicesSlice = never;

/**
 * Content for Bloc testimonial documents
 */
interface BlockTestimonialDocumentData {
  /**
   * Titre field in *Bloc testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Contenu field in *Bloc testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Testimonial texte 1 field in *Bloc testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.testimonial_text_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_text_1: prismic.KeyTextField;

  /**
   * Testimonial vignette 1 field in *Bloc testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.testimonial_vignette_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonial_vignette_1: prismic.ImageField<never>;

  /**
   * Testimonial texte 2 field in *Bloc testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.testimonial_text_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_text_2: prismic.KeyTextField;

  /**
   * Testimonial vignette 2 field in *Bloc testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.testimonial_vignette_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonial_vignette_2: prismic.ImageField<never>;

  /**
   * Testimonial texte 3 field in *Bloc testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.testimonial_text_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_text_3: prismic.KeyTextField;

  /**
   * Testimonial vignette 3 field in *Bloc testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.testimonial_vignette_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonial_vignette_3: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Bloc testimonial*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: block_testimonial.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlockTestimonialDocumentDataSlicesSlice>;
}

/**
 * Bloc testimonial document from Prismic
 *
 * - **API ID**: `block_testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlockTestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlockTestimonialDocumentData>,
    "block_testimonial",
    Lang
  >;

/**
 * Item in *Page d'accueil → Bloc thématiques*
 */
export interface HomepageDocumentDataBlockThematiquesItem {
  /**
   * Liste des thématiques field in *Page d'accueil → Bloc thématiques*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.block_thematiques[].thematics_list
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  thematics_list: prismic.ContentRelationshipField<"page_thematique">;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Page d'accueil documents
 */
interface HomepageDocumentData {
  /**
   * Titre field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Bloc Hero field in *Page d'accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.block_hero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  block_hero: prismic.ContentRelationshipField<"block_hero">;

  /**
   * Bloc testimonial field in *Page d'accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.block_testimonial
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  block_testimonial: prismic.ContentRelationshipField<"block_testimonial">;

  /**
   * Bloc thématiques field in *Page d'accueil*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.block_thematiques[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block_thematiques: prismic.GroupField<
    Simplify<HomepageDocumentDataBlockThematiquesItem>
  >;

  /**
   * Call to action field in *Page d'accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.block_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  block_cta: prismic.ContentRelationshipField<"block_cta">;

  /**
   * Contact field in *Page d'accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *Page d'accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page d'accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page d'accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page d'accueil document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageArticleDocumentDataSlicesSlice = never;

/**
 * Content for Page article documents
 */
interface PageArticleDocumentData {
  /**
   * Titre field in *Page article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Thématique field in *Page article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.thematic
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  thematic: prismic.ContentRelationshipField<"page_thematique">;

  /**
   * Sous-titre field in *Page article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Bannière field in *Page article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.banner_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_image: prismic.ImageField<never>;

  /**
   * Contenu field in *Page article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Auteur field in *Page article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Page article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page article document from Prismic
 *
 * - **API ID**: `page_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PageArticleDocumentData>,
    "page_article",
    Lang
  >;

/**
 * Item in *Page thématique → Listes des articles*
 */
export interface PageThematiqueDocumentDataArticlesItem {
  /**
   * Association pages field in *Page thématique → Listes des articles*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.articles[].association_pages
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  association_pages: prismic.ContentRelationshipField;
}

type PageThematiqueDocumentDataSlicesSlice = never;

/**
 * Content for Page thématique documents
 */
interface PageThematiqueDocumentData {
  /**
   * Titre field in *Page thématique*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sous-titre field in *Page thématique*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Vignette (page d'accueil) field in *Page thématique*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.image_vignette
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_vignette: prismic.ImageField<never>;

  /**
   * Bannière field in *Page thématique*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.image_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_banner: prismic.ImageField<never>;

  /**
   * En-tête field in *Page thématique*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.resume
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  resume: prismic.RichTextField;

  /**
   * Contenu field in *Page thématique*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Listes des articles field in *Page thématique*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.articles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<PageThematiqueDocumentDataArticlesItem>
  >;

  /**
   * Auteur field in *Page thématique*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page thématique*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_thematique.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageThematiqueDocumentDataSlicesSlice> /**
   * Meta Title field in *Page thématique*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page_thematique.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page thématique*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page_thematique.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Page thématique document from Prismic
 *
 * - **API ID**: `page_thematique`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageThematiqueDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PageThematiqueDocumentData>,
    "page_thematique",
    Lang
  >;

export type AllDocumentTypes =
  | BlockCtaDocument
  | BlockHeroDocument
  | BlockTestimonialDocument
  | HomepageDocument
  | PageArticleDocument
  | PageThematiqueDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlockCtaDocument,
      BlockCtaDocumentData,
      BlockCtaDocumentDataSlicesSlice,
      BlockHeroDocument,
      BlockHeroDocumentData,
      BlockHeroDocumentDataSlicesSlice,
      BlockTestimonialDocument,
      BlockTestimonialDocumentData,
      BlockTestimonialDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBlockThematiquesItem,
      HomepageDocumentDataSlicesSlice,
      PageArticleDocument,
      PageArticleDocumentData,
      PageArticleDocumentDataSlicesSlice,
      PageThematiqueDocument,
      PageThematiqueDocumentData,
      PageThematiqueDocumentDataArticlesItem,
      PageThematiqueDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
